baseURL = "https://umarharoon.com/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Umar Haroon"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3
[[menu.main]]
name = "Experiences"
url = "#resume"
weight = 4
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1

[params]
blogPageURL = "blog"
resumeURL = "resume"
contactLink = "contact"
copyright = "All right reserved copyright © Umar Haroon 2023"
footerLogo = "images/site-navigation/logo192.png"
# We're using formspree.io for form handling, paste your formspree url below
getformURL  = "https://getform.io/f/a5b7b431-b84e-4ac4-b065-d82f4ae85ee9"
googleAnalytics = "G-9145PR72NN"
logo = "images/site-navigation/logo192.png"

[params.address]
address = "Denver, CO"
linkedin = "Connect with me"
github = "View my work"
resume = "View my experiences"

[params.map]
# APIkey = "AIzaSyDnE0arfqtAgXq2ZMSr3uoN8JzG0wazTeM"
APIkey = "AIzaSyBRwXsfdEDBGKI-JcVzIfRyKNF2QBWWa-g"
latitude = "47.626952"
longitude = "-122.336785"
latitude1 = "32.776665"
longitude1 = "-96.796989"
pinImage = "images/pin.png"


# Social icons
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/umar__haroon/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "http://linkedin.com/in/umar-haroon/"
weight = 2
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/Umar-M-Haroon"
weight = 3

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'witchhazel'
    tabWidth = 4
